---
openapi: 3.0.2
info:
  title: Аудит API
  description: API для обращения к Platform V Audit
  contact:
    name: API Support
    url: https://sberbank.ru
  license:
    name: SberLicense
    url: https://sberbank.ru
  version: 2.0.1
paths:
  /v2/metamodel:
    post:
      tags:
        - Метамодель
      summary: Отправить метамодель
      description: Запрос на регистрацию метамодели в Platform V Audit
      operationId: uploadMetamodel
      requestBody:
        description: Метамодель
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/auditMetamodel"
      responses:
        201:
          description: Created
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/baseResponse"
        400:
          description: Bad Request
        401:
          description: Unauthorized
        403:
          description: Forbidden
        404:
          description: Not Found
        413:
          description: Payload Too Large
        415:
          description: Unsupported Media Type
        429:
          description: Too Many Requests
        500:
          description: Internal Server Error
        503:
          description: Service Unavailable

  /v2/event:
    post:
      tags:
        - Событие
      summary: Отправить событие
      description: Запрос на регистрацию события в Platform V Audit
      operationId: uploadEvent
      parameters:
        - in: header
          name: X-Node-ID
          description: IP и FQDN (через пробел) узла АС или FQDN namespace АС в OpenShift,
            с которого происходит отправка событий аудита
          schema:
            type: string
          required: true
        - in: header
          name: X-Request-ID
          description: Сквозной идентификатор события
          schema:
            type: string
          required: false
      requestBody:
        description: Событие
        required: true
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/auditEvent"
      responses:
        201:
          description: Created
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/baseResponse"
        400:
          description: Bad Request
        401:
          description: Unauthorized
        402:
          description: Payment Required
        403:
          description: Forbidden
        404:
          description: Not Found
        413:
          description: Payload Too Large
        415:
          description: Unsupported Media Type
        419:
          description: Insufficient Space On Resource
        426:
          description: Upgrade Required
        429:
          description: Too Many Requests
        500:
          description: Internal Server Error
        503:
          description: Service Unavailable

  /v2/events:
    post:
      tags:
        - Пакет событий
      summary: Отправить пакет событий
      description: Запрос на регистрацию пакета событий в Platform V Audit
      operationId: uploadEvents
      parameters:
        - in: header
          name: X-Node-ID
          description: IP и FQDN (через пробел) узла АС или FQDN namespace АС в OpenShift,
            с которого происходит отправка событий аудита
          schema:
            type: string
          required: true
        - in: header
          name: X-Request-ID
          description: Сквозной идентификатор события
          schema:
            type: string
          required: false
      requestBody:
        description: Пакет событий
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                "$ref": "#/components/schemas/auditBatchEvent"
      responses:
        201:
          description: Created
          content:
            application/json:
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/auditBatchResponse"
        400:
          description: Bad Request
        401:
          description: Unauthorized
        402:
          description: Payment Required
        403:
          description: Forbidden
        404:
          description: Not Found
        413:
          description: Payload Too Large
        415:
          description: Unsupported Media Type
        419:
          description: Insufficient Space On Resource
        426:
          description: Upgrade Required
        429:
          description: Too Many Requests
        500:
          description: Internal Server Error
        503:
          description: Service Unavailable

components:
  schemas:
    auditMetamodel:
      type: object
      required:
        - metamodelVersion
        - module
        - events
      properties:
        metamodelVersion:
          type: string
          minLength: 1
          maxLength: 300
          description: Версия метамодели
        module:
          type: string
          minLength: 1
          maxLength: 300
          description: Идентификатор модуля
        events:
          type: array
          minItems: 1
          items:
            type: object
            description: Список описаний событий аудита
            required:
              - name
              - description
              - mode
              - success
            properties:
              name:
                type: string
                description: Наименование события аудита
              description:
                type: string
                description: Описание события
              success:
                type: boolean
                description: Признак успешного события
              mode:
                type: string
                description: Режим отправки события
                enum:
                  - speed
                  - reliability
              params:
                type: array
                description: Перечень параметров события аудита
                items:
                  type: object
                  required:
                    - name
                    - description
                  properties:
                    name:
                      type: string
                      description: Наименование параметра события аудита
                    description:
                      type: string
                      description: Описание параметра события аудита
              changedParams:
                type: array
                description: Список изменённых атрибутов бизнес-сущности АС
                items:
                  type: object
                  required:
                    - name
                    - description
                  properties:
                    name:
                      type: string
                      description: Наименование изменяемого атрибута
                    description:
                      type: string
                      description: Описание изменяемого атрибута
    auditEvent:
      type: object
      required:
        - module
        - createdAt
        - metamodelVersion
        - name
        - userNode
        - userLogin
      properties:
        metamodelVersion:
          type: string
          minLength: 1
          maxLength: 300
          description: Версия метамодели
        name:
          type: string
          minLength: 1
          description: Наименование события аудита
        session:
          type: string
          description: Идентификатор сессии (если есть)
        module:
          type: string
          minLength: 1
          maxLength: 300
          description: Идентификатор модуля
        createdAt:
          type: integer
          format: int64
          minimum: 1000000000000
          description: Время возникновения события в милисекундах (Unix time)
        userLogin:
          type: string
          description: Логин пользователя
        userName:
          type: string
          description: Имя пользователя (для систем не интегрированных с ППРБ Platform
            V IAM (SPAS))
        userNode:
          type: string
          description: Узел/Компьютер пользователя инициатора события (IP/FQDN)
        params:
          type: array
          description: Список параметров события
          items:
            type: object
            required:
              - name
            properties:
              name:
                type: string
                minLength: 1
                description: Наименование параметра
              value:
                type: string
                description: Значение параметра
        tags:
          type: array
          description: Теги, позволяющие группировать события
          items:
            type: string
        changedParams:
          type: array
          description: Список изменённых атрибутов бизнес-сущности АС
          items:
            type: object
            required:
              - name
              - value
              - oldValue
            properties:
              name:
                type: string
                minLength: 1
                description: Наименование атрибута
              value:
                type: string
                description: Новое значение атрибута
              oldValue:
                type: string
                description: Предыдущее значение атрибута
    auditBatchEvent:
      type: object
      required:
        - uuid
        - event
      properties:
        uuid:
          type: string
          format: uuid
          description: Идентификатор, необходимый для сопоставления запроса и ответа
        event:
          "$ref": "#/components/schemas/auditEvent"
    auditBatchError:
      type: object
      required:
        - uuid
        - error
      properties:
        uuid:
          type: string
          format: uuid
          description: Идентификатор, необходимый для сопоставления запроса и ответа
        error:
          "$ref": "#/components/schemas/baseError"
    auditBatchResponse:
      type: object
      required:
        - identifiers
      properties:
        identifiers:
          type: array
          description: Идентификаторы Событий/Метамоделей в Аудите
          items:
            type: string
    baseError:
      type: object
      properties:
        code:
          type: string
          description: Код ошибки
        message:
          type: string
          description: Сообщение
        description:
          type: string
          description: Описание
    baseResponse:
      type: object
      properties:
        id:
          type: string
          description: Идентификатор События/Метамодели в Аудите
