@startuml
'https://plantuml.com/sequence-diagram
autonumber
==Изменение партнера==
Клиент -> ППРБ.Партнеры: PUT /partners
ППРБ.Партнеры -> СББОЛ: /counterparty/check-migration/{digitalId}
alt#Gold #lightblue appobj UfsCounterpartiesDictionaryMigratedToPartners = false
СББОЛ --> ППРБ.Партнеры: Клиент не мигрирован в ППРБ
ППРБ.Партнеры -> ППРБ.Партнеры: Поиск партнера в partner
alt#Gold Есть запись в таблице partner и partner.type != "renter"
ППРБ.Партнеры -> СББОЛ: /update/{digitalId} (изменение партнера по СББОЛ correspondent.replication_guid)
СББОЛ --> ППРБ.Партнеры: 200
break#Gold #Pink Ошибка. Прерывание операции
СББОЛ --> ППРБ.Партнеры: Error 40*/50*
ППРБ.Партнеры --> Клиент: Error 40*/50*
end
par#gold
ППРБ.Партнеры --> Клиент: 200
ППРБ.Партнеры -> ППРБ.Партнеры: Обновление данных в таблице partner, phone, email
end
else Есть запись партнера в таблице partner и partner.type = "renter"
ППРБ.Партнеры -> ППРБ.Партнеры: Обновление данных в таблице partner и phone, email
ППРБ.Партнеры --> Клиент: 200
else Нет записи в partner
ППРБ.Партнеры -> СББОЛ: /update/{digitalId} (изменение партнера по СББОЛ correspondent.replication_guid)
СББОЛ --> ППРБ.Партнеры: 200
break#Gold #Pink Ошибка. Прерывание операции
СББОЛ --> ППРБ.Партнеры: Error 40*/50*
ППРБ.Партнеры --> Клиент: Error 40*/50*
end
par#gold
ППРБ.Партнеры --> Клиент: 200
ППРБ.Партнеры -> ППРБ.Партнеры: Создание записи в таблице partner, phone, email
end
end
else #white appobj UfsCounterpartiesDictionaryMigratedToPartners = true
СББОЛ --> ППРБ.Партнеры: Клиент мигрирован в ППРБ
ППРБ.Партнеры -> ППРБ.Партнеры: Поиск партнера в partner
alt#gold Есть запись в таблице partner и partner.type != "renter"
ППРБ.Партнеры -> ППРБ.Партнеры: Обновление записи в таблице partner, email, phone
par#gold
ППРБ.Партнеры --> Клиент: 200
ППРБ.Партнеры -> СББОЛ: /update/{digitalId} (изменение партнера по replication_history.uuid)
СББОЛ -> ППРБ.Партнеры: 200
group#Gold #pink negative
СББОЛ --> ППРБ.Партнеры: Error 40*/50*
ППРБ.Партнеры -> ФП.Журналирование: Отправка месседжа в СББОЛ через кафку
ППРБ.Партнеры -> Мониторинг: Оповещение об ошибке
Мониторинг -> BRAIN_TEAM: Разбор ошибки и подготовка исправлений
СББОЛ ->> ФП.Журналирование: Считывание очереди
СББОЛ -> СББОЛ: Создание записи
end
end
else Есть запись в таблице partner и partner.type = "renter"
ППРБ.Партнеры -> ППРБ.Партнеры: Обновление записи в таблице partner, email, phone
ППРБ.Партнеры --> Клиент: 200
else Нет записи в partner
break#Gold #pink Нет записи, прерывание операции
ППРБ.Партнеры --> Клиент: 40* ошибка
end
end
end
@enduml
