@startuml
'https://plantuml.com/sequence-diagram
autonumber
==Создание счетов==
Клиент -> ППРБ.Партнеры: POST /partners/accounts
ППРБ.Партнеры -> СББОЛ: /counterparty/check-migration/{digitalId}
alt#Gold #lightblue appobj UfsCounterpartiesDictionaryMigratedToPartners = false
СББОЛ --> ППРБ.Партнеры: Клиент не мигрирован в ППРБ
ППРБ.Партнеры -> ППРБ.Партнеры: Поиск партнера в partner
alt#Gold Есть запись в partner и partner.type = "renter"
ППРБ.Партнеры -> ППРБ.Партнеры: Создание записи в account, bank, bank_account
ППРБ.Партнеры --> Клиент: 200
else Запись в partner != "renter" или нет записи в partner
ППРБ.Партнеры --> СББОЛ: /{digitalId}/{pprbGuid} поиск партнера по replication_guid
СББОЛ --> ППРБ.Партнеры: 200
alt#gold  Заполнен один из 3ех параметров account, bic, bank_account
break#Gold #Pink Ошибка. Попытка создать более 1 счета на партнера
ППРБ.Партнеры --> Клиент: Error 40*
end
else Не заполнен не один из 3ех параметров account, bic, bank_account
ППРБ.Партнеры -> СББОЛ: /update/{digitalId} (изменение account, bic, bank_account партнера по partner.uuid = correspondent.replication_guid)
СББОЛ --> ППРБ.Партнеры: 200
ППРБ.Партнеры --> Клиент: 200
end
end
else #white appobj UfsCounterpartiesDictionaryMigratedToPartners = true
СББОЛ --> ППРБ.Партнеры: Клиент мигрирован в ППРБ
ППРБ.Партнеры -> ППРБ.Партнеры: Поиск партнера по partner_uuid в partner
alt#Gold Есть запись в таблице partner и partner.type != "renter"
ППРБ.Партнеры -> ППРБ.Партнеры: Поиск связанных с партнером счетов в таблице account
alt#gold В таблице account нет связанных счетов с партнером
ППРБ.Партнеры -> ППРБ.Партнеры: Создание записи в account, bank, bank_account
par#gold
ППРБ.Партнеры --> Клиент: 200
ППРБ.Партнеры -> СББОЛ: /update/{digitalId} (изменение account, bic, bank_account партнера по partner.uuid = correspondent.pprb_guid or correspondent.replication_guid)
end
СББОЛ --> ППРБ.Партнеры: 200
group#Gold #Pink negative
СББОЛ --> ППРБ.Партнеры: Error 50*/40*
ППРБ.Партнеры -> ФП.Журналирование: Отправка месседжа в СББОЛ через кафку
ППРБ.Партнеры -> Мониторинг: Оповещение об ошибке
Мониторинг -> BRAIN_TEAM: Разбор ошибки и подготовка исправлений
СББОЛ ->> ФП.Журналирование: Считывание очереди
СББОЛ -> СББОЛ: Создание записи
end
else В таблице account есть связанные счета с партнером
break#Gold #Pink Ошибка. Попытка создать более 1 счета на партнера
ППРБ.Партнеры --> Клиент: Error 40*
end
end
else Есть партнер в таблице partner с partner.type = "renter"
ППРБ.Партнеры -> ППРБ.Партнеры: Создание записи в account, bank, bank_account
ППРБ.Партнеры --> Клиент: 200
else В таблице partner отсутствует партнер
break#Gold #Pink Ошибка. Отсутствует партнер
ППРБ.Партнеры --> Клиент: Error 40*
end
end
end
@enduml
