@startuml
'https://plantuml.com/sequence-diagram
autonumber
==Удаление партнера==
Клиент -> ППРБ.Партнеры: DELETE /partner/{digitalId}/{id}
ППРБ.Партнеры -> СББОЛ: /counterparty/check-migration/{digitalId}
alt#Gold #lightblue appobj UfsCounterpartiesDictionaryMigratedToPartners = false
СББОЛ --> ППРБ.Партнеры: Клиент не мигрирован в ППРБ
ППРБ.Партнеры -> ППРБ.Партнеры: Поиск записи в partner
alt#Gold Есть запись партнера в таблице и partner.type != "renter"
ППРБ.Партнеры -> СББОЛ: /delete/{digitalId}/{pprbGuid} (удалить партнера c pprb_guid = correspondent.replication_guid)
break#Gold #Pink Ошибка. Прерывание операции
СББОЛ --> ППРБ.Партнеры: Error 40*/50*
ППРБ.Партнеры --> Клиент: Error 40*/50*
end
СББОЛ --> ППРБ.Партнеры: 200
ППРБ.Партнеры --> Клиент: 204
ППРБ.Партнеры -> ППРБ.Партнеры: Удаление партнера в таблицах partner и всех связанных записей в phone, email, account, bank, bank_account, document, contact, address
else Есть запись партнера в таблице partner и partner.type = "renter"
ППРБ.Партнеры -> ППРБ.Партнеры: Удаление партнера в таблицах partner и всех связанных записей в phone, email, account, bank, bank_account, document, contact, address
ППРБ.Партнеры --> Клиент: 204
else Нет записи в таблице partner
ППРБ.Партнеры -> СББОЛ: /delete/{digitalId}/{pprbGuid} (удалить партнера c pprb_guid = correspondent.replication_guid)
break#Gold #Pink Ошибка. Прерывание операции
СББОЛ --> ППРБ.Партнеры: Error 40*/50*
ППРБ.Партнеры --> Клиент: Error 40*/50*
end
СББОЛ --> ППРБ.Партнеры: 200
ППРБ.Партнеры --> Клиент: 204
end
else #white appobj UfsCounterpartiesDictionaryMigratedToPartners = true
СББОЛ --> ППРБ.Партнеры: Клиент мигрирован в ППРБ
ППРБ.Партнеры -> ППРБ.Партнеры: Поиск записи в partner
alt#Gold Есть запись партнера в таблице partner.type != "renter"
ППРБ.Партнеры -> ППРБ.Партнеры: Удаление партнера в таблицах partner, phone, email, account, bank, bank_account
par#gold
ППРБ.Партнеры --> Клиент: 204
ППРБ.Партнеры -> СББОЛ: /delete/{digitalId}/{pprbGuid} (удалить партнера c pprb_guid = partner.uuid)
СББОЛ -> ППРБ.Партнеры: 200
group#Gold #pink negative
СББОЛ --> ППРБ.Партнеры: Error 40*/50*
ППРБ.Партнеры -> ФП.Журналирование: Отправка месседжа в СББОЛ через кафку
ППРБ.Партнеры -> Мониторинг: Оповещение об ошибке
Мониторинг -> BRAIN_TEAM: Разбор ошибки и подготовка исправлений
СББОЛ ->> ФП.Журналирование: Считывание очереди
СББОЛ -> СББОЛ: Удаление записей
end
end
else partner.type = "renter"
ППРБ.Партнеры -> ППРБ.Партнеры: Удаление партнера в таблицах partner, phone, email, account, bank, bank_account
ППРБ.Партнеры --> Клиент: 204
else Нет записи в таблице partner
break#gold #pink
ППРБ.Партнеры --> Клиент: 404
end
end
end
@enduml
