@startuml
'https://plantuml.com/sequence-diagram
autonumber
==Изменение партнера==
Клиент -> ППРБ.Партнеры: PUT /partners
ППРБ.Партнеры -> СББОЛ: /counterparty/check-migration/{digitalId}
alt#Gold #lightblue appobj UfsCounterpartiesDictionaryMigratedToPartners = false
СББОЛ --> ППРБ.Партнеры: Клиент не мигрирован в ППРБ
break#Gold #Pink Ошибка. Прерывание операции
ППРБ.Партнеры --> Клиент: Error 400 [клиент не мигрирован]
end
else #white appobj UfsCounterpartiesDictionaryMigratedToPartners = true
СББОЛ --> ППРБ.Партнеры: Клиент мигрирован в ППРБ
ППРБ.Партнеры -> ППРБ.Партнеры: Поиск партнера в partner
ППРБ.Партнеры -> ППРБ.Партнеры: Обновление записи в таблице partner, email, phone
ППРБ.Партнеры --> Клиент: 200
else Нет записи в partner
break#Gold #pink Нет записи, прерывание операции
ППРБ.Партнеры --> Клиент: 400 ошибка
end
end
@enduml
