kind: ConfigMap
apiVersion: v1
metadata:
  labels:
    app.kubernetes.io/component: istio-discovery
    app.kubernetes.io/instance: ${ISTIO_CONTROL_PLANE}
    app.kubernetes.io/managed-by: maistra-istio-operator
    app.kubernetes.io/name: istio-discovery
    app.kubernetes.io/part-of: istio
    app.kubernetes.io/version: 2.0.2-3.el8-76
    istio.io/rev: basic
    maistra-version: 2.0.2
    maistra.io/owner: ${ISTIO_CONTROL_PLANE}
    release: istio
  name: cm-egress-istio-basic
data:
  mesh: |-
    accessLogEncoding: TEXT
    accessLogFile: /dev/stdout
    accessLogFormat: ""
    defaultConfig:
      concurrency: 2
      configPath: ./etc/istio/proxy
      controlPlaneAuthPolicy: NONE
      discoveryAddress: istiod-basic.${ISTIO_CONTROL_PLANE}.svc:15012
      drainDuration: 45s
      parentShutdownDuration: 1m0s
      proxyAdminPort: 15000
      proxyMetadata:
        DNS_AGENT: ""
      serviceCluster: istio-proxy
      tracing:
        tlsSettings:
          caCertificates: null
          clientCertificate: null
          mode: DISABLE
          privateKey: null
          sni: null
          subjectAltNames: []
        zipkin:
          address: jaeger-collector.${ISTIO_CONTROL_PLANE}.svc:9411
    disableMixerHttpReports: true
    disablePolicyChecks: true
    enableAutoMtls: true
    enableEnvoyAccessLogService: false
    enablePrometheusMerge: false
    enableTracing: true
    ingressClass: istio
    ingressControllerMode: STRICT
    ingressService: istio-egressgateway
    localityLbSetting:
      enabled: true
    outboundTrafficPolicy:
      mode: ALLOW_ANY
    protocolDetectionTimeout: 5000ms
    reportBatchMaxEntries: 100
    reportBatchMaxTime: 1s
    rootNamespace: ${ISTIO_CONTROL_PLANE}
    sdsUdsPath: unix:/etc/istio/proxy/SDS
    trustDomain: cluster.local
    trustDomainAliases: null
  meshNetworks: 'networks: {}'
