kind: ConfigMap
apiVersion: v1
metadata:
  name: cm-ingress-ott-logback
data:
  logback.xml: |-
    <?xml version="1.0" encoding="UTF-8"?>
    <configuration scan="true" scanPeriod="60 seconds">
        <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
            <encoder>
                <pattern>%X{ott.req.id} %d{HH:mm:ss.SSS} [%-5level] [%logger{36}] [%thread] - %msg%n</pattern>
            </encoder>
        </appender>

        <appender name="FILE" class="ch.qos.logback.core.FileAppender">
            <file>/tmp/OttTest.log</file>
            <append>false</append>
            <encoder>
                <pattern>%X{ott.req.id} %d{HH:mm:ss.SSS} [%-5level] [%logger{36}] [%thread] - %msg%n</pattern>
            </encoder>
        </appender>
        <root level="info">
            <appender-ref ref="STDOUT"/>
            <appender-ref ref="FILE"/>
        </root>
        <logger name="com.sbt.ott" level="info"/>
        <logger name="com.sbt.ott.api.rest" level="error"/>
        <logger name="com.sbt.core" level="error"/>
        <logger name="com.fasterxml" level="error"/>
    </configuration>