commons:
  ci:
    credentials: CAB-SA-CI000825
  openshift:
    credentials: CAB-SA-CI000825
    url: api.dev-gen2.sigma.sbrf.ru:6443
  nexus:
    credentials: CAB-SA-CI000825
    url: sbtatlas.sigma.sbrf.ru/nexus
    snapshotRepository: corp-snapshots
    releaseRepository: corp-releases
  registry:
    credentials: CAB-SA-CI000825
    url: registry.sigma.sbrf.ru
    snapshotProject: pprb-dev/ci00908578/ci02792425_sbbol-partners_dev
    releaseProject: pprb/ci00908578/ci02792425_sbbol-partners
  git:
    credentials: dataspace-bot-ssh
  sonar:
    credentials: dataspace-bot-sonar-key
    url: https://sbt-sonarqube.sigma.sbrf.ru/
    token: 613f5c708cf709538c6ae732f47a922458b4f1db
  maven:
    pathSettings: ./config/sbbol/settings.xml