-- liquibase formatted sql
--changeset 17480332:1640097483333_delete_dataspace_structure

DROP TABLE
    LC_REPL_CR_CRBATCH_IDENTIFIERS,
    T_REPL_AGGLOCK_CRLOCK,
    T_REPL_AGGLOCK_RENTER,
    T_REPL_AGGLOCK_ROOTDICTIONARY,
    T_REPL_AGGLOCKEVENT,
    T_REPL_CR_CRAGGREGATETASK,
    T_REPL_CR_CRBATCH,
    T_REPL_CR_CREPKEVENT,
    T_REPL_CR_CREPKEVENTBUFFER,
    T_REPL_CR_CRLOCK,
    T_REPL_CR_CRPROCESS,
    T_REPL_CR_CRREQUESTEVENT,
    T_REPL_CR_CRREQUESTEVENT_DUP_BY_AGGREGATE,
    T_REPL_CR_CRTASK,
    T_REPL_CR_INIT_SUBTASK,
    T_REPL_CR_INIT_TASK,
    T_ROOTDICTIONARY;
