openapi: "3.0.3"
info:
  title: Request for documents
  version: 1.0.0
  description: OpenAPI Specification for partner document

servers:
  - url: /

paths:
  /partner/accounts/sign:
    put:
      tags:
        - Accounts Sign
      description: Обновление подписи счёта
      operationId: update
      requestBody:
        description: Обновление статуса подписания счёта
        required: true
        content:
          application/json:
            schema:
              $ref: 'model/sign/accounts_sign_status.json'
      responses:
        200:
          description: Успешный ответ
          content:
            application/json:
              schema:
                $ref: 'model/sign/accounts_sign_response.json'
        404:
          description: Not Found
        400:
          description: Bad Request
        401:
          description: Unauthorized
        403:
          description: Forbidden

  /partner/accounts/sign/view:
    post:
      tags:
        - Accounts Sign
      description: Получение подписи счетов
      operationId: list
      requestBody:
        description: Статус подписи счетов
        required: true
        content:
          application/json:
            schema:
              $ref: 'model/sign/accounts_sign_filter.json'
      responses:
        200:
          description: Успешный ответ
          content:
            application/json:
              schema:
                $ref: 'model/sign/accounts_sign_response.json'
        404:
          description: Not Found
        400:
          description: Bad Request
        401:
          description: Unauthorized
        403:
          description: Forbidden
