openapi: "3.0.3"
info:
  title: Request for partners account sign
  version: 1.1.7
  description: OpenAPI Specification for partner account sign

servers:
  - url: /

paths:
  /partner/accounts/sign:
    post:
      tags:
        - Accounts Sign
      description: Подпись
      operationId: create
      parameters:
        - name: Fraud-Meta-Data
          in: header
          required: true
          schema:
            $ref: 'model/fraud/fraud_meta_data.json'
          description: Метаданные для ФРОД-мониторинга
      requestBody:
        description: Подписание счёта партнера
        required: true
        content:
          application/json:
            schema:
              $ref: 'model/sign/accounts_sign_info.json'
      responses:
        200:
          description: Успешный ответ
          content:
            application/json:
              schema:
                $ref: 'model/sign/accounts_sign_info_response.json'
        404:
          description: Not Found
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: 'model/common/error.json'
        401:
          description: Unauthorized
        403:
          description: Forbidden

  /partner/accounts/sign/{digitalId}/{accountId}:
    get:
      tags:
        - Accounts Sign
      description: Проверка подписи аккаунта
      operationId: get-by-id
      parameters:
        - name: digitalId
          in: path
          required: true
          schema:
            type: string
          description: Идентификатор личного кабинета
        - name: accountId
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: Идентификатор счёта
      responses:
        200:
          description: Успешный ответ
          content:
            application/json:
              schema:
                $ref: 'model/sign/account_sign_info.json'
        404:
          description: Not Found
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: 'model/common/error.json'
        401:
          description: Unauthorized
        403:
          description: Forbidden

  /partner/accounts/sign/{digitalId}:
    delete:
      tags:
        - Accounts Sign
      description: Удаление подписи счёта по идентификатору аккаунта
      operationId: delete
      parameters:
        - name: digitalId
          in: path
          required: true
          schema:
            type: string
          description: Идентификатор личного кабинета
        - name: accountIds
          in: query
          required: true
          schema:
            type: array
            minItems: 1
            maxItems: 200
            items:
              type: string
              format: uuid
          description: Идентификатор счёта
      responses:
        204:
          description: Успешный ответ
        404:
          description: Not Found
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: 'model/common/error.json'
        401:
          description: Unauthorized
        403:
          description: Forbidden

  /partner/accounts/sign/info:
    post:
      tags:
        - Accounts Sign
      description: Проверка подписи по реквизитам
      operationId: get-sign-info-by-requisites
      requestBody:
        description: Реквизиты счета
        required: true
        content:
          application/json:
            schema:
              $ref: 'model/sign/account_sign_info_requisites.json'
      responses:
        200:
          description: Успешный ответ
          content:
            application/json:
              schema:
                $ref: 'model/sign/account_sign_info_requisites_response.json'
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: 'model/common/error.json'
        401:
          description: Unauthorized
        403:
          description: Forbidden
        404:
          description: Not Found
