openapi: "3.0.3"
info:
  title: Request for contact email
  version: 1.0.2
  description: OpenAPI Specification for contact email

servers:
  - url: /

paths:
  /partner/contact/emails/view:
    post:
      tags:
        - Contact Email
      description: Получения Email адресов контакта
      operationId: list
      requestBody:
        description: Фильтр для запроса email адресов контактов
        required: true
        content:
          application/json:
            schema:
              $ref: 'model/email/emails_filter.json'
      responses:
        200:
          description: Успешный ответ
          content:
            application/json:
              schema:
                $ref: 'model/email/emails_response.json'
        404:
          description: Not Found
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: 'model/common/error.json'
        401:
          description: Unauthorized
        403:
          description: Forbidden

  /partner/contact/emails/{digitalId}:
    delete:
      tags:
        - Contact Email
      description: Удаление email контакта
      operationId: delete
      parameters:
        - name: digitalId
          in: path
          required: true
          schema:
            type: string
          description: Идентификатор личного кабинета
        - name: ids
          in: query
          required: true
          schema:
            type: array
            items:
              type: string
              maxItems: 200
          description: Идентификатор электронного адреса
      responses:
        204:
          description: Успешный ответ
        404:
          description: Not Found
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: 'model/common/error.json'
        401:
          description: Unauthorized
        403:
          description: Forbidden

  /partner/contact/email:
    post:
      tags:
        - Contact Email
      description: Создание электронных адресов контакта
      operationId: create
      requestBody:
        description: Адреса
        required: true
        content:
          application/json:
            schema:
              $ref: 'model/email/email_create.json'
      responses:
        201:
          description: Успешный ответ
          content:
            application/json:
              schema:
                $ref: 'model/email/email.json'
        404:
          description: Not Found
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: 'model/common/error.json'
        401:
          description: Unauthorized
        403:
          description: Forbidden
    put:
      tags:
        - Contact Email
      description: Обновление электронных адресов контакта
      operationId: update
      requestBody:
        description: Emails
        required: true
        content:
          application/json:
            schema:
              $ref: 'model/email/email.json'
      responses:
        200:
          description: Успешный ответ
          content:
            application/json:
              schema:
                $ref: 'model/email/email.json'
        404:
          description: Not Found
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: 'model/common/error.json'
        401:
          description: Unauthorized
        403:
          description: Forbidden
