openapi: "3.0.3"
info:
  title: Request for contact address
  version: 1.0.0
  description: OpenAPI Specification for contact address

servers:
  - url: /

paths:
  /partner/contact/addresses/view:
    post:
      tags:
        - Contact Address
      description: Получения адресов контакта
      operationId: list
      requestBody:
        description: Фильтр для запроса адресов контактов
        required: true
        content:
          application/json:
            schema:
              $ref: 'model/address/addresses_filter.json'
      responses:
        200:
          description: Успешный ответ
          content:
            application/json:
              schema:
                $ref: 'model/address/addresses_response.json'
        404:
          description: Not Found
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: 'model/common/error.json'
        401:
          description: Unauthorized
        403:
          description: Forbidden

  /partner/contact/addresses/{digitalId}/{id}:
    get:
      tags:
        - Contact Address
      description: Получение адреса по его идентификатору
      operationId: get-by-id
      parameters:
        - name: digitalId
          in: path
          required: true
          schema:
            type: string
          description: Идентификатор личного кабинета
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: Идентификатор адреса
      responses:
        200:
          description: Успешный ответ
          content:
            application/json:
              schema:
                $ref: 'model/address/address.json'
        404:
          description: Not Found
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: 'model/common/error.json'
        401:
          description: Unauthorized
        403:
          description: Forbidden

  /partner/contact/addresses/{digitalId}:
    delete:
      tags:
        - Contact Address
      description: Удаление адреса контакта
      operationId: delete
      parameters:
        - name: digitalId
          in: path
          required: true
          schema:
            type: string
          description: Идентификатор личного кабинета
        - name: ids
          in: query
          required: true
          schema:
            type: array
            items:
              type: string
              maxItems: 200
          description: Идентификатор адреса
      responses:
        204:
          description: Успешный ответ
        404:
          description: Not Found
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: 'model/common/error.json'
        401:
          description: Unauthorized
        403:
          description: Forbidden

  /partner/contact/address:
    post:
      tags:
        - Contact Address
      description: Создание адресов контакта
      operationId: create
      requestBody:
        description: Адреса
        required: true
        content:
          application/json:
            schema:
              $ref: 'model/address/address_create.json'
      responses:
        201:
          description: Успешный ответ
          content:
            application/json:
              schema:
                $ref: 'model/address/address.json'
        404:
          description: Not Found
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: 'model/common/error.json'
        401:
          description: Unauthorized
        403:
          description: Forbidden
    put:
      tags:
        - Contact Address
      description: Обновление адресов контакта
      operationId: update
      requestBody:
        description: Адреса
        required: true
        content:
          application/json:
            schema:
              $ref: 'model/address/address.json'
      responses:
        200:
          description: Успешный ответ
          content:
            application/json:
              schema:
                $ref: 'model/address/address.json'
        404:
          description: Not Found
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: 'model/common/error.json'
        401:
          description: Unauthorized
        403:
          description: Forbidden
