openapi: "3.0.3"
info:
  title: Request for contact phone number
  version: 1.1.0
  description: OpenAPI Specification for contact phone number

servers:
  - url: /

paths:
  /partner/contact/phones/view:
    post:
      tags:
        - Contact Phone
      description: Получения номеров телефона контакта
      operationId: list
      requestBody:
        description: Фильтр для запроса номеров телефона контактов
        required: true
        content:
          application/json:
            schema:
              $ref: 'model/phone/phones_filter.json'
      responses:
        200:
          description: Успешный ответ
          content:
            application/json:
              schema:
                $ref: 'model/phone/phones_response.json'
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: 'model/common/error.json'
        401:
          description: Unauthorized
        403:
          description: Forbidden

  /partner/contact/phones/{digitalId}:
    delete:
      tags:
        - Contact Phone
      description: Удаление номера телефона контакта
      operationId: delete
      parameters:
        - name: digitalId
          in: path
          required: true
          schema:
            type: string
          description: Идентификатор личного кабинета
        - name: ids
          in: query
          required: true
          schema:
            type: array
            items:
              type: string
              maxItems: 200
          description: Идентефикатор номера телефона
      responses:
        204:
          description: Успешный ответ
        404:
          description: Not Found
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: 'model/common/error.json'
        401:
          description: Unauthorized
        403:
          description: Forbidden

  /partner/contact/phone:
    post:
      tags:
        - Contact Phone
      description: Создание телефонов контакта
      operationId: create
      requestBody:
        description: Номер телефонов
        required: true
        content:
          application/json:
            schema:
              $ref: 'model/phone/phone_create.json'
      responses:
        201:
          description: Успешный ответ
          content:
            application/json:
              schema:
                $ref: 'model/phone/phone.json'
        404:
          description: Not Found
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: 'model/common/error.json'
        401:
          description: Unauthorized
        403:
          description: Forbidden
    put:
      tags:
        - Contact Phone
      description: Обновление номера телефонов контакта
      operationId: update
      requestBody:
        description: Телефоны
        required: true
        content:
          application/json:
            schema:
              $ref: 'model/phone/phone.json'
      responses:
        200:
          description: Успешный ответ
          content:
            application/json:
              schema:
                $ref: 'model/phone/phone.json'
        404:
          description: Not Found
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: 'model/common/error.json'
        401:
          description: Unauthorized
        403:
          description: Forbidden
