openapi: "3.0.3"
info:
  title: Request for documents
  version: 1.0.0
  description: OpenAPI Specification for document

servers:
  - url: /

paths:
  /dictionary/documents/view:
    post:
      tags:
        - Document Type Dictionary
      description: Получение справочника видов документа
      operationId: list
      requestBody:
        description: Фильтр для запроса видов документа
        required: true
        content:
          application/json:
            schema:
              $ref: 'model/dictionary/document_type_filter.json'
      responses:
        200:
          description: Успешный ответ
          content:
            application/json:
              schema:
                $ref: 'model/dictionary/documents_type_response.json'
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: 'model/common/error.json'
        401:
          description: Unauthorized
        403:
          description: Forbidden

  /dictionary/documents:
    post:
      tags:
        - Document Type Dictionary
      description: Создание нового вида документа
      operationId: create
      requestBody:
        description: Описание нового вида документа
        required: true
        content:
          application/json:
            schema:
              $ref: 'model/dictionary/document_type_create.json'
      responses:
        201:
          description: Успешный ответ
          content:
            application/json:
              schema:
                $ref: 'model/dictionary/document_type.json'
        404:
          description: Not Found
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: 'model/common/error.json'
        401:
          description: Unauthorized
        403:
          description: Forbidden
    put:
      tags:
        - Document Type Dictionary
      description: Обновление статуса у вида документа
      operationId: update
      requestBody:
        description: Новый статус вида документа
        required: true
        content:
          application/json:
            schema:
              $ref: 'model/dictionary/document_type_change.json'
      responses:
        200:
          description: Успешный ответ
          content:
            application/json:
              schema:
                $ref: 'model/dictionary/document_type.json'
        404:
          description: Not Found
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: 'model/common/error.json'
        401:
          description: Unauthorized
        403:
          description: Forbidden
  /dictionary/documents/{id}:
    delete:
      tags:
        - Document Type Dictionary
      description: Удаление вида документа
      operationId: delete
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: Идентификатор типа документа
      responses:
        204:
          description: Успешный ответ
        404:
          description: Not Found
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: 'model/common/error.json'
        401:
          description: Unauthorized
        403:
          description: Forbidden
