openapi: "3.0.3"
info:
  title: Request for documents
  version: 1.0.0
  description: OpenAPI Specification for dictionary

servers:
  - url: /

paths:
  /dictionary/budget-mask:
    post:
      tags:
        - Budget Mask Dictionary
      description: Создание записи в справочнике масок бюджетности
      operationId: create
      requestBody:
        description: Описание новой записи справочника
        required: true
        content:
          application/json:
            schema:
              $ref: 'model/dictionary/budget_mask.json'
      responses:
        201:
          description: Успешный ответ
          content:
            application/json:
              schema:
                $ref: 'model/dictionary/budget_mask.json'
        404:
          description: Not Found
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: 'model/common/error.json'
        401:
          description: Unauthorized
        403:
          description: Forbidden
    delete:
      tags:
        - Budget Mask Dictionary
      description: Удаление записи в справочнике масок бюджетности
      operationId: delete
      parameters:
        - name: ids
          in: query
          required: true
          schema:
            type: array
            items:
              type: string
              maxItems: 200
          description: Идентификатор маски
      responses:
        204:
          description: Успешный ответ
        404:
          description: Not Found
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: 'model/common/error.json'
        401:
          description: Unauthorized
        403:
          description: Forbidden

  /dictionary/budget-mask/view:
    post:
      tags:
        - Budget Mask Dictionary
      description: Получение списка масок бюджетности
      operationId: list
      requestBody:
        description: Фильтр для запроса масок бюджетности
        required: true
        content:
          application/json:
            schema:
              $ref: 'model/dictionary/budget_mask_filter.json'
      responses:
        200:
          description: Успешный ответ
          content:
            application/json:
              schema:
                $ref: 'model/dictionary/budget_masks_response.json'
        404:
          description: Not Found
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: 'model/common/error.json'
        401:
          description: Unauthorized
        403:
          description: Forbidden
