openapi: "3.0.3"
info:
  title: Request for documents
  version: 1.0.0
  description: OpenAPI Specification for document

servers:
  - url: /

paths:
  /dictionary/documents/{status}:
    get:
      tags:
        - Document Type Dictionary
      description: Получение справочника видов документа
      operationId: list
      parameters:
        - name: status
          in: path
          required: true
          schema:
            type: boolean
          description: Признак удаленного или актуального вида документа true удален false актуальный
      responses:
        200:
          description: Успешный ответ
          content:
            application/json:
              schema:
                $ref: 'model/dictionary/documents_type_response.json'
        400:
          description: Bad Request
        401:
          description: Unauthorized
        403:
          description: Forbidden

  /dictionary/documents:
    post:
      tags:
        - Document Type Dictionary
      description: Создание нового вида документа
      operationId: create
      requestBody:
        description: Описание нового вида документа
        required: true
        content:
          application/json:
            schema:
              $ref: 'model/dictionary/document_type.json'
      responses:
        201:
          description: Успешный ответ
          content:
            application/json:
              schema:
                $ref: 'model/dictionary/document_type_response.json'
        404:
          description: Not Found
        400:
          description: Bad Request
        401:
          description: Unauthorized
        403:
          description: Forbidden
    put:
      tags:
        - Document Type Dictionary
      description: Обновление статуса у вида документа
      operationId: update
      requestBody:
        description: Новый статус вида документа
        required: true
        content:
          application/json:
            schema:
              $ref: 'model/dictionary/document_type.json'
      responses:
        200:
          description: Успешный ответ
          content:
            application/json:
              schema:
                $ref: 'model/dictionary/document_type_response.json'
        404:
          description: Not Found
        400:
          description: Bad Request
        401:
          description: Unauthorized
        403:
          description: Forbidden
