openapi: "3.0.3"
info:
  title: Request for dictionary budget mask
  version: 1.0.5
  description: OpenAPI Specification for dictionary

servers:
  - url: /

paths:
  /dictionary/budget-mask/view:
    post:
      tags:
        - Budget Mask Dictionary
      description: Получение списка масок бюджетности
      operationId: list
      requestBody:
        description: Фильтр для запроса масок бюджетности
        required: true
        content:
          application/json:
            schema:
              $ref: 'model/dictionary/budget_mask_filter.json'
      responses:
        200:
          description: Успешный ответ
          content:
            application/json:
              schema:
                $ref: 'model/dictionary/budget_masks_response.json'
        404:
          description: Not Found
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: 'model/common/error.json'
        401:
          description: Unauthorized
        403:
          description: Forbidden
