openapi: "3.0.3"
info:
  title: Request for dictionary documents
  version: 1.0.14
  description: OpenAPI Specification for document

servers:
  - url: /

paths:
  /dictionary/documents/view:
    post:
      tags:
        - Document Type Dictionary
      description: Получение справочника видов документа
      operationId: list
      requestBody:
        description: Фильтр для запроса видов документа
        required: true
        content:
          application/json:
            schema:
              $ref: 'model/dictionary/document_type_filter.json'
      responses:
        200:
          description: Успешный ответ
          content:
            application/json:
              schema:
                $ref: 'model/dictionary/documents_type_response.json'
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: 'model/common/error.json'
        401:
          description: Unauthorized
        403:
          description: Forbidden
