openapi: "3.0.3"
info:
  title: Request for partners
  version: 1.0.0
  description: OpenAPI Specification for partners

servers:
  - url: /

paths:
  /partners/{digitalId}/{id}:
    get:
      tags:
        - Partners
      description: Получение Партнера по его идентификатору
      operationId: get-by-id
      parameters:
        - name: digitalId
          in: path
          required: true
          schema:
            type: string
          description: Идентефикатор личного кабинета
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: Идентефикатор партнера
      responses:
        200:
          description: Успешинй ответ
          content:
            application/json:
              schema:
                $ref: 'model/partners/partner_response.json'
        404:
          description: Not Found
        400:
          description: Bad Request
        401:
          description: Unauthorized
        403:
          description: Forbidden
    delete:
      tags:
        - Partners
      description: Удаление Партнера
      operationId: delete
      parameters:
        - name: digitalId
          in: path
          required: true
          schema:
            type: string
          description: Идентефикатор личного кабинета
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: Идентефикатор партнера
      responses:
        204:
          description: Успешный ответ
        404:
          description: Not Found
        400:
          description: Bad Request
        401:
          description: Unauthorized
        403:
          description: Forbidden

  /partners:
    post:
      tags:
        - Partners
      description: Создание партнера
      operationId: create
      requestBody:
        description: Партнер
        required: true
        content:
          application/json:
            schema:
              $ref: 'model/partners/partner.json'
      responses:
        201:
          description: Успешный ответ
          content:
            application/json:
              schema:
                $ref: 'model/partners/partner_response.json'
        404:
          description: Not Found
        400:
          description: Bad Request
        401:
          description: Unauthorized
        403:
          description: Forbidden
    put:
      tags:
        - Partners
      description: Обновление Партнера
      operationId: update
      requestBody:
        description: Партнер
        required: true
        content:
          application/json:
            schema:
              $ref: 'model/partners/partner.json'
      responses:
        200:
          description: Успешный ответ
          content:
            application/json:
              schema:
                $ref: 'model/partners/partner_response.json'
        404:
          description: Not Found
        400:
          description: Bad Request
        401:
          description: Unauthorized
        403:
          description: Forbidden

  /partners/view:
    post:
      tags:
        - Partners
      description: Получение Партнеров
      operationId: list
      requestBody:
        description: Фильтр для запроса Партнеров
        required: true
        content:
          application/json:
            schema:
              $ref: 'model/partners/partners_filter.json'
      responses:
        200:
          description: Успешный ответ
          content:
            application/json:
              schema:
                $ref: 'model/partners/partners_response.json'
        404:
          description: Not Found
        400:
          description: Bad Request
        401:
          description: Unauthorized
        403:
          description: Forbidden

  /partners/merge:
    post:
      tags:
        - Partners merge
      description: Слияние партнеров
      operationId: merge-by-partners
      requestBody:
        description: Слияние партнеров
        required: true
        content:
          application/json:
            schema:
              $ref: 'model/merge/parnters_merge.json'
      responses:
        200:
          description: Успешный ответ
          content:
            application/json:
              schema:
                $ref: 'model/merge/partners_merge_response.json'
        404:
          description: Not Found
        400:
          description: Bad Request
        401:
          description: Unauthorized
        403:
          description: Forbidden
