openapi: "3.0.3"
info:
  title: Request for partners
  version: 1.1.8
  description: OpenAPI Specification for partners

servers:
  - url: /

paths:
  /partners/{digitalId}/{id}:
    get:
      tags:
        - Partners
      description: Получение Партнера по его идентификатору
      operationId: get-by-id
      parameters:
        - name: digitalId
          in: path
          required: true
          schema:
            type: string
          description: Идентификатор личного кабинета
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: Идентификатор партнера
      responses:
        200:
          description: Успешный ответ
          content:
            application/json:
              schema:
                $ref: 'model/partners/partner.json'
        404:
          description: Not Found
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: 'model/common/error.json'
        401:
          description: Unauthorized
        403:
          description: Forbidden

  /partners/{digitalId}:
    delete:
      tags:
        - Partners
      description: Удаление Партнера
      operationId: delete
      parameters:
        - name: digitalId
          in: path
          required: true
          schema:
            type: string
          description: Идентификатор личного кабинета
        - name: ids
          in: query
          required: true
          schema:
            type: array
            minItems: 1
            maxItems: 200
            items:
              type: string
              format: uuid
          description: Идентификатор партнера
        - name: Fraud-Meta-Data
          in: header
          required: true
          schema:
            $ref: 'model/fraud/fraud_meta_data.json'
          description: Метаданные для ФРОД-мониторинга
      responses:
        204:
          description: Успешный ответ
        404:
          description: Not Found
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: 'model/common/error.json'
        401:
          description: Unauthorized
        403:
          description: Forbidden

  /partner:
    post:
      tags:
        - Partners
      description: Создание партнеров
      operationId: create
      requestBody:
        description: Партнеры
        required: true
        content:
          application/json:
            schema:
              $ref: 'model/partners/partner_create.json'
      responses:
        201:
          description: Успешный ответ
          content:
            application/json:
              schema:
                $ref: 'model/partners/partner.json'
        404:
          description: Not Found
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: 'model/common/error.json'
        401:
          description: Unauthorized
        403:
          description: Forbidden
    put:
      tags:
        - Partners
      description: Обновление Партнеров
      operationId: update
      requestBody:
        description: Партнер
        required: true
        content:
          application/json:
            schema:
              $ref: 'model/partners/partner.json'
      responses:
        200:
          description: Успешный ответ
          content:
            application/json:
              schema:
                $ref: 'model/partners/partner.json'
        404:
          description: Not Found
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: 'model/common/error.json'
        401:
          description: Unauthorized
        403:
          description: Forbidden

  /partner/full-model:
    post:
      tags:
        - Partners
      description: Создание партнера
      operationId: create-full-model
      requestBody:
        description: Партнеры
        required: true
        content:
          application/json:
            schema:
              $ref: 'model/partners/partner_create_full_model.json'
      responses:
        201:
          description: Успешный ответ
          content:
            application/json:
              schema:
                $ref: 'model/partners/partner_full_model_response.json'
        404:
          description: Not Found
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: 'model/common/error.json'
        401:
          description: Unauthorized
        403:
          description: Forbidden

  /partner/full-model/patch:
    post:
      tags:
        - Partners
      description: Обновление партнера
      operationId: patch-full-model
      requestBody:
        description: Партнеры
        required: true
        content:
          application/json:
            schema:
              $ref: 'model/partners/partner_change_full_model.json'
      responses:
        200:
          description: Успешный ответ
          content:
            application/json:
              schema:
                $ref: 'model/partners/partner_full_model_response.json'
        404:
          description: Not Found
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: 'model/common/error.json'
        401:
          description: Unauthorized
        403:
          description: Forbidden

  /partners/view:
    post:
      tags:
        - Partners
      description: Получение Партнеров
      operationId: list
      requestBody:
        description: Фильтр для запроса Партнеров
        required: true
        content:
          application/json:
            schema:
              $ref: 'model/partners/partners_filter.json'
      responses:
        200:
          description: Успешный ответ
          content:
            application/json:
              schema:
                $ref: 'model/partners/partners_response.json'
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: 'model/common/error.json'
        401:
          description: Unauthorized
        403:
          description: Forbidden
