LiquibaseRoll:
  mainDb:
    dbUrl: jdbc:postgresql://10.53.223.100:5433/partners_main
    dbUser: rental_property
    dbPassword: rentalproperty
    tableSpace: pg_default
    dbDriver: org.postgresql.Driver
Installer:
  openShiftUrl: api.dev-gen2.sigma.sbrf.ru:6443
  openShiftProject: ci02281165-edevgen2-efs-kib-sbbol-dev-test10
  ingressGatewayName: gw-ds-ingress
  setUniqModuleName: false
  setUniqName: false
  parameters:
    dataspace-core-template:
      mainDataBaseSecretId: main-db-secret
      MODULE_NAME: dataspace-core-partners
      standinEnabled: false
      FLUENTBIT_IMAGE: registry.sigma.sbrf.ru/pprb/ci00641491/ci02469991_logger/fluent-bit:1.4.5
      requestCPU: 500m
      requestMemory: 1024Mi
      limitMemory: 2048Mi
    dataspace-gigabas-template:
      MODULE_NAME: dataspace-gigabas-partners
      MODEL_PACKAGE_NAME: TODODELETE
      requestCPU: 500m
      requestMemory: 1024Mi
      FLUENTBIT_IMAGE: registry.sigma.sbrf.ru/pprb/ci00641491/ci02469991_logger/fluent-bit:1.4.5
    partners-template:
      MODULE_NAME: sbbol-partners
      dataSpaceCoreUrl: "http://svc-dataspace-core-partners:8080"
      requestCPU: 500m
      requestMemory: 1024Mi
      FLUENTBIT_IMAGE: registry.sigma.sbrf.ru/pprb/ci00641491/ci02469991_logger/fluent-bit:1.4.5
      needInstallOutRoute: true