openapi: "3.0.3"
info:
  title: Request for partners account
  version: 1.0.0
  description: OpenAPI Specification for partners account

servers:
  - url: /

paths:
  /partner/accounts/view:
    post:
      tags:
        - Partner Accounts
      description: Получение счётов Партнера
      operationId: list
      requestBody:
        description: Фильтр для запроса счётов Партнера
        required: true
        content:
          application/json:
            schema:
              $ref: 'model/accounts/accounts_filter.json'
      responses:
        200:
          description: Успешный ответ
          content:
            application/json:
              schema:
                $ref: 'model/accounts/accounts_response.json'
        404:
          description: Not Found
        400:
          description: Bad Request
        401:
          description: Unauthorized
        403:
          description: Forbidden

  /partner/account/{digitalId}/{id}:
    get:
      tags:
        - Partner Accounts
      description: Получение счётов по его идентефикатору
      operationId: get-by-id
      parameters:
        - name: digitalId
          in: path
          required: true
          schema:
            type: string
          description: Идентификатор личного кабинета
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: Идентефикатор счёта
      responses:
        200:
          description: Успешный ответ
          content:
            application/json:
              schema:
                $ref: 'model/accounts/account_response.json'
        404:
          description: Not Found
        400:
          description: Bad Request
        401:
          description: Unauthorized
        403:
          description: Forbidden
    delete:
      tags:
        - Partner Accounts
      description: Удаление счёта Партнера
      operationId: delete
      parameters:
        - name: digitalId
          in: path
          required: true
          schema:
            type: string
          description: Идентификатор личного кабинета
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: Идентефикатор счёта
      responses:
        204:
          description: Успешный ответ
        404:
          description: Not Found
        400:
          description: Bad Request
        401:
          description: Unauthorized
        403:
          description: Forbidden

  /partner/account:
    post:
      tags:
        - Partner Accounts
      description: Создание счётов партнера
      operationId: create
      requestBody:
        description: Счёта
        required: true
        content:
          application/json:
            schema:
              $ref: 'model/accounts/account_create.json'
      responses:
        201:
          description: Успешный ответ
          content:
            application/json:
              schema:
                $ref: 'model/accounts/account_response.json'
        404:
          description: Not Found
        400:
          description: Bad Request
        401:
          description: Unauthorized
        403:
          description: Forbidden
    put:
      tags:
        - Partner Accounts
      description: Обновление счётов Партнера
      operationId: update
      requestBody:
        description: Счёта
        required: true
        content:
          application/json:
            schema:
              $ref: 'model/accounts/account_change.json'
      responses:
        200:
          description: Успешный ответ
          content:
            application/json:
              schema:
                $ref: 'model/accounts/account_response.json'
        404:
          description: Not Found
        400:
          description: Bad Request
        401:
          description: Unauthorized
        403:
          description: Forbidden

  /partner/account/priority:
    put:
      tags:
        - Partner Accounts
      description: Изменение признака приоритетности аккаунта
      operationId: change
      requestBody:
        description: Счёта
        required: true
        content:
          application/json:
            schema:
              $ref: 'model/accounts/account_priority.json'
      responses:
        201:
          description: Успешный ответ
          content:
            application/json:
              schema:
                $ref: 'model/accounts/account_response.json'
        404:
          description: Not Found
        400:
          description: Bad Request
        401:
          description: Unauthorized
        403:
          description: Forbidden
