openapi: "3.0.3"
info:
  title: Request for documents
  version: 1.0.0
  description: OpenAPI Specification for partner document

servers:
  - url: /

paths:
  /partner/accounts/sign:
    post:
      tags:
        - Accounts Sign
      description: Подпись
      operationId: create
      requestBody:
        description: Подписание счёта партнера
        required: true
        content:
          application/json:
            schema:
              $ref: 'model/sign/accounts_sign_info.json'
      responses:
        200:
          description: Успешный ответ
          content:
            application/json:
              schema:
                $ref: 'model/sign/accounts_sign_info_response.json'
        404:
          description: Not Found
        400:
          description: Bad Request
        401:
          description: Unauthorized
        403:
          description: Forbidden

  /partner/accounts/sign/view:
    post:
      tags:
        - Accounts Sign
      description: Получение подписи счетов
      operationId: list
      requestBody:
        description: Статус подписи счетов
        required: true
        content:
          application/json:
            schema:
              $ref: 'model/sign/accounts_sign_filter.json'
      responses:
        200:
          description: Успешный ответ
          content:
            application/json:
              schema:
                $ref: 'model/sign/accounts_sign_response.json'
        404:
          description: Not Found
        400:
          description: Bad Request
        401:
          description: Unauthorized
        403:
          description: Forbidden

  /partner/accounts/sign/{digitalId}/{accountId}:
    get:
      tags:
        - Accounts Sign
      description: Проверка подписи аккаунта
      operationId: get-by-id
      parameters:
        - name: digitalId
          in: path
          required: true
          schema:
            type: string
          description: Идентификатор личного кабинета
        - name: accountId
          in: path
          required: true
          schema:
            type: string
          description: Идентификатор счёта
      responses:
        200:
          description: Успешный ответ
          content:
            application/json:
              schema:
                $ref: 'model/sign/account_sign_info.json'
        404:
          description: Not Found
        400:
          description: Bad Request
        401:
          description: Unauthorized
        403:
          description: Forbidden
    delete:
      tags:
        - Accounts Sign
      description: Удаление подписи счёта по идентификатору аккаунта
      operationId: delete
      parameters:
        - name: digitalId
          in: path
          required: true
          schema:
            type: string
          description: Идентификатор личного кабинета
        - name: accountId
          in: path
          required: true
          schema:
            type: string
          description: Идентификатор счёта
      responses:
        204:
          description: Успешный ответ
        404:
          description: Not Found
        400:
          description: Bad Request
        401:
          description: Unauthorized
        403:
          description: Forbidden
