kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app: egressgateway-${NAMESPACE}
    app.kubernetes.io/component: gateways
    app.kubernetes.io/instance: ${ISTIO_CONTROL_PLANE}
    app.kubernetes.io/managed-by: maistra-istio-operator
    app.kubernetes.io/name: gateways
    app.kubernetes.io/part-of: istio
    app.kubernetes.io/version: 2.0.2-3.el8-76
    chart: gateways
    heritage: Tiller
    istio: egressgateway-${NAMESPACE}
    maistra-version: 2.0.2
    maistra.io/owner: ${ISTIO_CONTROL_PLANE}
    release: istio
  name: egressgateway-${NAMESPACE}
spec:
  progressDeadlineSeconds: 600
  replicas: ${EGRESS_REPLICAS_COUNT}
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: egressgateway-${NAMESPACE}
      istio: egressgateway-${NAMESPACE}
  strategy:
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      creationTimestamp: null
      labels:
        app: egressgateway-${NAMESPACE}
        chart: gateways
        heritage: Tiller
        istio: egressgateway-${NAMESPACE}
        release: istio
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - preference:
                matchExpressions:
                  - key: beta.kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
              weight: 2
            - preference:
                matchExpressions:
                  - key: beta.kubernetes.io/arch
                    operator: In
                    values:
                      - ppc64le
              weight: 2
            - preference:
                matchExpressions:
                  - key: beta.kubernetes.io/arch
                    operator: In
                    values:
                      - s390x
              weight: 2
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: beta.kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
                      - ppc64le
                      - s390x
      containers:
        - args:
            - proxy
            - router
            - --domain
            - $(POD_NAMESPACE).svc.cluster.local
            - --proxyLogLevel=warning
            - --proxyComponentLogLevel=misc:error
            - --log_output_level=default:info
            - --serviceCluster
            - egressgateway-${NAMESPACE}
            - --trust-domain=cluster.local
          env:
            - name: JWT_POLICY
              value: first-party-jwt
            - name: PILOT_CERT_PROVIDER
              value: istiod
            - name: CA_ADDR
              value: istiod-basic.${ISTIO_CONTROL_PLANE}.svc:15012
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: INSTANCE_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.hostIP
            - name: SERVICE_ACCOUNT
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.serviceAccountName
            - name: CANONICAL_SERVICE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.labels['service.istio.io/canonical-name']
            - name: CANONICAL_REVISION
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.labels['service.istio.io/canonical-revision']
            - name: ISTIO_META_WORKLOAD_NAME
              value: egressgateway-${NAMESPACE}
            - name: ISTIO_META_OWNER
              value: kubernetes://apis/apps/v1/namespaces/${NAMESPACE}/deployments/egressgateway-${NAMESPACE}
            - name: ISTIO_META_MESH_ID
              value: cluster.local
            - name: ISTIO_META_ROUTER_MODE
              value: sni-dnat
            - name: ISTIO_META_CLUSTER_ID
              value: Kubernetes
          image: ${PROXY_IMAGE}
          imagePullPolicy: IfNotPresent
          name: istio-proxy
          ports:
            - containerPort: 8080
              name: http2
              protocol: TCP
            - containerPort: 8443
              name: https
              protocol: TCP
            - containerPort: 15443
              name: tls
              protocol: TCP
            - containerPort: 15090
              name: http-envoy-prom
              protocol: TCP
          readinessProbe:
            failureThreshold: 30
            httpGet:
              path: /healthz/ready
              port: 15021
              scheme: HTTP
            initialDelaySeconds: 1
            periodSeconds: 2
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              cpu: ${EGRESS_LIMIT_CPU}
              memory: ${EGRESS_LIMIT_MEMORY}
              ephemeral-storage: ${EGRESS_PROXY_LIMIT_EPHEMERAL_STORAGE}
            requests:
              cpu: ${EGRESS_REQUEST_CPU}
              memory: ${EGRESS_REQUEST_MEMORY}
              ephemeral-storage: ${EGRESS_PROXY_REQUEST_EPHEMERAL_STORAGE}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /etc/istio/proxy
              name: istio-envoy
            - mountPath: /etc/istio/config
              name: config-volume
            - mountPath: /etc/istio/pod
              name: podinfo
            - mountPath: /etc/istio/egressgateway-certs
              name: egressgateway-certs
              readOnly: true
            - mountPath: /etc/istio/egressgateway-ca-certs
              readOnly: true
              name: egressgateway-ca-certs
        - resources:
            limits:
              cpu: 400m
              memory: 500Mi
              ephemeral-storage: ${EGRESS_OTT_LIMIT_EPHEMERAL_STORAGE}
            requests:
              cpu: 300m
              memory: 300Mi
              ephemeral-storage: ${EGRESS_OTT_REQUEST_EPHEMERAL_STORAGE}
          terminationMessagePath: /dev/termination-log
          name: ott-sidecar
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 8443
              protocol: TCP
            - containerPort: 8778
              protocol: TCP
            - name: http-envoy-prom
              containerPort: 15090
              protocol: TCP
          imagePullPolicy: Always
          volumeMounts:
            - name: ott-secret
              readOnly: true
              mountPath: /mnt/secrets
            - name: ott-uds-socket
              mountPath: /mnt/ott-uds-socket
            - name: ott-logback
              readOnly: true
              mountPath: /tmp/ott-logback.xml
          terminationMessagePolicy: File
          envFrom:
            - secretRef:
                name: ott-ingress-passwords
            - configMapRef:
                name: cm-egress-ott-settings
          image: ${OTT_REGISTRY_URL}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - configMap:
            defaultMode: 400
            name: istio-ca-root-cert
          name: istiod-ca-cert
        - downwardAPI:
            defaultMode: 400
            items:
              - fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.labels
                path: labels
              - fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.annotations
                path: annotations
          name: podinfo
        - emptyDir: {}
          name: istio-envoy
        - configMap:
            defaultMode: 400
            name: cm-egress-istio-basic
            optional: true
          name: config-volume
        - name: egressgateway-certs
          secret:
            secretName: istio-egressgateway-certs
            defaultMode: 400
            optional: true
        - name: egressgateway-ca-certs
          secret:
            secretName: istio-egressgateway-ca-certs
            defaultMode: 400
            optional: true
        - name: ott-secret
          secret:
            secretName: ott-secret
            defaultMode: 400
        - name: ott-uds-socket
          emptyDir:
            medium: Memory
        - name: ott-logback
          configMap:
            name: cm-egress-ott-logback
            defaultMode: 400
