Installer:
  openShiftUrl: api.dev-gen.sigma.sbrf.ru:6443
  openShiftProject: ci00684783-edevgen-dataspace-core-dev
  ingressGatewayName: gw-ds-ingress
  setUniqModuleName: false
  parameters:
    dataspace-core-template:
      MODULE_NAME: dataspace-core-deposit
      standinEnabled: false
      FLUENTBIT_IMAGE: registry.sigma.sbrf.ru/pprb/ci00641491/ci02469991_logger/fluent-bit:1.4.5
      requestCPU: 500m
      limitCPU: 1500m
      limitMemory: 1500Mi
      requestMemory: 1024Mi
    dataspace-gigabas-template:
      MODULE_NAME: dataspace-gigabas-deposit
      MODEL_PACKAGE_NAME: TODODELETE
      requestCPU: 750m
      requestMemory: 1024Mi
      FLUENTBIT_IMAGE: registry.sigma.sbrf.ru/pprb/ci00641491/ci02469991_logger/fluent-bit:1.4.5
    dataspace-client-template:
      MODULE_NAME: deposit-service
      dataSpaceCoreUrl: "http://svc-dataspace-core-deposit:8080"
      limitCPU: 1500m
      limitMemory: 1500Mi
      requestCPU: 500m
      requestMemory: 1024Mi
      needInstallOutRoute: true
      FLUENTBIT_IMAGE: registry.sigma.sbrf.ru/pprb/ci00641491/ci02469991_logger/fluent-bit:1.4.5
      ACCOUNT_SERVICE_ENABLED: false
      ACCOUNT_SERVICE_URL: "http://svc-account-service:8080"