@startuml
'https://plantuml.com/sequence-diagram
autonumber
==Создание партнера==
Клиент -> СББОЛ: Создание партнера
СББОЛ -> СББОЛ: Проверка на миграцию
alt#Gold #lightblue appobj UfsCounterpartiesDictionaryMigratedToPartners = false
СББОЛ -> СББОЛ: Создать контрагента
СББОЛ --> Клиент: Информация о контрагенте
else #white appobj UfsCounterpartiesDictionaryMigratedToPartners = true
СББОЛ -> СББОЛ: Изменить аппобж на false
end
==GET/VIEW==
note right of СББОЛ
Внезависимости от аппобжа.
Методы get/view не влияют на аппобж
end note
Клиент -> СББОЛ: GET/VIEW /counterparty/...
СББОЛ --> Клиент: 200
@enduml
