@startuml
'https://plantuml.com/sequence-diagram
autonumber
==Создание рентера==
Клиент -> ППРБ.Партнеры: Создание партнера (old)
ППРБ.Партнеры -> ППРБ.Партнеры: Создать рентера по старой модели
ППРБ.Партнеры --> Клиент: Информация о рентере по старой модели
@enduml
