kind: Service
apiVersion: v1
metadata:
  name: egressgateway-svc
  labels:
    app: egressgateway-${NAMESPACE}
    istio: egressgateway-${NAMESPACE}
spec:
  ports:
    - name: tcp-8080
      port: 8080
      protocol: TCP
    - name: tcp-${DB_TCP_PORT}
      port: ${DB_TCP_PORT}
      protocol: TCP
    - name: tcp-${DB_SI_TCP_PORT}
      port: ${DB_SI_TCP_PORT}
    - name: http-${EGRESS_HTTPS_PORT}
      port: ${EGRESS_HTTPS_PORT}
      protocol: TCP
    - name: http-${EGRESS_OTT_PORT}
      port: ${EGRESS_OTT_PORT}
      protocol: TCP
    - name: tcp-8081
      port: 8081
      protocol: TCP
  selector:
    app: egressgateway-${NAMESPACE}
    istio: egressgateway-${NAMESPACE}
  type: ClusterIP
  sessionAffinity: None