kind: Service
apiVersion: v1
metadata:
  labels:
    app: ingressgateway-${NAMESPACE}
    istio: ingressgateway-${NAMESPACE}
  name: ingressgateway-svc
spec:
  ports:
    - name: https-${INGRESS_PORT_HTTPS}
      port: ${INGRESS_PORT_HTTPS}
    - name: https-${INGRESS_OTT_PORT}
      port: ${INGRESS_OTT_PORT}
  selector:
    app: ingressgateway-${NAMESPACE}
    istio: ingressgateway-${NAMESPACE}
  type: ClusterIP