kind: Service
apiVersion: v1
metadata:
  labels:
    app: ingressgateway-${NAMESPACE}
    istio: ingressgateway-${NAMESPACE}
  name: ingressgateway-svc
spec:
  ports:
    - name: https-${INGRESS_GEO_TLS_PORT}
      port: ${INGRESS_GEO_TLS_PORT}
    - name: https-${INGRESS_TLS_PORT}
      port: ${INGRESS_TLS_PORT}
    - name: https-${INGRESS_GEO_OTT_PORT}
      port: ${INGRESS_GEO_OTT_PORT}
    - name: https-${INGRESS_OTT_PORT}
      port: ${INGRESS_OTT_PORT}
    - name: https-${INGRESS_HEALTH_CHECK_PORT}
      port: ${INGRESS_HEALTH_CHECK_PORT}
  selector:
    app: ingressgateway-${NAMESPACE}
    istio: ingressgateway-${NAMESPACE}
  type: ClusterIP