### Настройки DevSecOps ###
### Общая информация о команде ###
team:
  - {
    # код команды в МУСе
    mus_code: "",
    # название команды в МУСе
    mus_name: "",
    # почтовый адрес Product Owner в МУСе для уведомлений с результатами сканирования. Возможно указание нескольких email через ;
    mus_po_mail: "",
  }

### Общая информация о приложении ###
app:
  # конфигурационный элемент КЭ приложения / модуля ПО в Service Manager
  sm_id: ""
  # название КЭ приложения / модуля ПО в Service Manager
  sm_name: ""
### Настройки SAST Checkmarx ###
sast_cx:
  # сredentials id в Jenkins для учетной записи Checkmarx одной команды, под которой будет проводиться сканирование
  creds_id: ""
  # проектная область в JIRA для заведения и синхронизации дефектов
  jira_area: ""
  # маски файлов и директорий для включения (**/*) в скан и исключения (!**/*) из скана
  masks: "!**/js/base-libs/**/*, !**/js/libs/**/*, !**/styles/_vendor/**/*, !**/stub/**/*, !**/generated/**/*, !**/node_modules/**/*, !**/build/**/*, !**/target/**/*, !**/src/test/**/*, !**/tests/**/*, !**/.pipeline/**/*, !**/_cvs/**/*, !**/.svn/**/*, !**/.hg/**/*, !**/.git/**/*, !**/.bzr/**/*, !**/bin/**/*, !**/obj/**/*, !**/backup/**/*, !**/.idea/**/*, !**/pom.xml, !**/*.DS_Store, !**/*.gradle, !**/*.ipr, !**/*.iws, !**/*.bak, !**/*.tmp, !**/*.aac, !**/*.aif, !**/*.iff, !**/*.m3u, !**/*.mid, !**/*.mp3, !**/*.mpa, !**/*.ra, !**/*.wav, !**/*.wma, !**/*.3g2, !**/*.3gp, !**/*.asf, !**/*.asx, !**/*.avi, !**/*.flv, !**/*.mov, !**/*.mp4, !**/*.mpg, !**/*.rm, !**/*.swf, !**/*.vob, !**/*.wmv, !**/*.bmp, !**/*.gif, !**/*.jpg, !**/*.png, !**/*.psd, !**/*.tif, !**/*.swf, !**/*.jar, !**/*.zip, !**/*.rar, !**/*.exe, !**/*.dll, !**/*.pdb, !**/*.7z, !**/*.gz, !**/*.tar.gz, !**/*.tar, !**/*.gz, !**/*.ahtm, !**/*.ahtml, !**/*.fhtml, !**/*.hdm, !**/*.hdml, !**/*.hsql, !**/*.ht, !**/*.hta, !**/*.htc, !**/*.htd, !**/*.war, !**/*.ear, !**/*.htmls, !**/*.ihtml, !**/*.mht, !**/*.mhtm, !**/*.mhtml, !**/*.ssi, !**/*.stm, !**/*.stml, !**/*.ttml, !**/*.txn, !**/*.xhtm, !**/*.xhtml, !**/*.class, !**/*.iml, !**/*.sh, !**/*.bat, !Checkmarx/Reports/*.*"
  #id профиля сканирования, по умолчанию 36. 14 - для мобильного приложения
  preset_id: "36"
  # макс время ожидания статуса QG в минутах
  wait_qg: "30"
  ###