commons:
  ci:
    credentials: DS_sbbol-nexus
  openshift:
    credentials: DS_sbbol-nexus
    url: api.dev-gen2.sigma.sbrf.ru:6443
  nexus:
    credentials: DS_sbbol-nexus
    url: sbtatlas.sigma.sbrf.ru/nexus
    snapshotRepository: corp-snapshots
    releaseRepository: corp-releases
  registry:
    credentials: DS_sbbol-nexus
    url: registry.sigma.sbrf.ru
    snapshotProject: pprb-dev/ci00908578/ci02792425_sbbol-partners_dev
    releaseProject: pprb/ci00908578/ci02792425_sbbol-partners
  git:
    credentials: dataspace-bot-ssh
  sonar:
    url: https://sbt-sonarqube.sigma.sbrf.ru/
    token: 826d76d27597ac41ae13d0811ca95c12ef12d57d
    projectKey: ru.sberbank.pprb.sbbol.partners:partners
  maven:
    pathSettings: ./config/pprbac/settings.xml

QualityGates:
  sbrf:
    url: https://sbrf-nexus.sigma.sbrf.ru/nexus
    groupId: Nexus_PROD.CI02792425_sbbol-partners
    credentials: DS_sbbol-nexus
    repositoryId: corp-releases
  sast:
    credentials: DS_SAST_PARTNERS
    configPath: config/devsecops-config.yml
  mode: scanAndFlags
