---
integration_entries:
  - "{{ int.pprb.appjournal.v1_0 }}"
  - "{{ int.pprb.db_main.v1_0 }}"
  - "{{ int.pprb.db_si.v1_0 }}"
  - "{{ int.sbbol.rest_in.latest }}"
  - "{{ int.pprb.fluentbit.v1_0 }}"

int_entry:
  pprb:
    db_main: "{{ int.pprb.db_main.v1_0 }}"
    db_si: "{{ int.pprb.db_si.v1_0 }}"
  sbbol:
    rest_in: "{{ int.sbbol.rest_in.latest }}"
