docker:
  images:
    java: registry.sigma.sbrf.ru/ci00149046/ci00405008_sbbolufs/bellsoft/liberica-openjdk-alpine:15.0.2-10-sber-certs
    postgres: registry.sigma.sbrf.ru/ci00149046/ci00405008_sbbolufs/postgres:13-alpine

credentials:
  sonar: DS_CAB-SA-CI000825-sonar-token
  nexus: DS_CAB-SA-CI000825
  checkmarx: DS_CAB-SA-CI000825-checkmarx
  openshift: DS_CAB-SA-CI000825-openshift

allure_project_id: '154'

pr_check:
  liquibase:
    match:
      files:
        - 'runner/src/main/resources/db/changelog'
    executable:
      download_uri: https://nexus.sigma.sbrf.ru/nexus/service/local/repositories/SBT_CI_distr_repo/content/SBBOL_UFS/liquibase/3.7.0-postgres/liquibase-3.7.0-postgres-bin.tar.gz
    changelog:
      path: runner/src/main/resources/db/changelog/changelog.yaml
    defaults_file:
      path: jenkins/resources/liquibase/liquibase.properties
  openshift:
    workdir: openshift

    match:
      files:
        - 'openshift/'
        - 'jenkins/resources/openshift/'
    server: dev-gen2
    namespace: ci02281165-edevgen2-efs-kib-sbbol-dev-test6
  build_gradle:
    match:
      files:
        - 'partners-adapter/'
        - 'partners-openapi/'
        - 'partners-service/'
        - 'buildSrc/'
        - 'docs/'
        - 'build.gradle.kts'
        - 'gradle.properties'
        - 'settings.gradle.kts'
    cpu: 1
    memory: '2g'
    command: >-
      ./gradlew
      -PnexusLogin=${env.NEXUS_USR}
      -PnexusPassword=${env.NEXUS_PWD}
      clean build -x test
  test:
    postgres: true
    match:
      files:
        - 'partners-adapter/'
        - 'partners-openapi/'
        - 'partners-service/'
        - 'buildSrc/'
        - 'docs/'
        - 'build.gradle.kts'
        - 'gradle.properties'
        - 'settings.gradle.kts'
        - 'jenkins/settings.yml'
        - 'jenkins/test.groovy'
    cpu: 2
    memory: '4g'
    command: >-
      ./gradlew
      -PnexusLogin=${env.NEXUS_USR}
      -PnexusPassword='${env.NEXUS_PWD}'
      -Dsonar.login=${env.SONAR_TOKEN}
      -Dsonar.projectVersion=${pullRequest.fromRef.displayId}
      -Dsonar.pullrequest.key=${params.pullRequestId}
      -Dsonar.pullrequest.branch=${pullRequest.fromRef.displayId}
      -Dsonar.pullrequest.base=${pullRequest.toRef.displayId}
      -Dtest.results.enabled=true
      -Dtest-layer=unit,api,configuration,cdcConsumer
      -Dallure.link=${Const.ALLURE_ENTRYPOINT_URL}jobrun/${launch.jobRunId}
      -Dbuild.link=${env.BUILD_URL}
      -Dbuild.type=prCheck
      -Pspring.datasource.url=jdbc:postgresql://${env.NETWORK_ALIAS_MAIN}/${env.POSTGRES_DB_NAME}
      -Pspring.datasource.username=${env.POSTGRES_DB_USER}
      -Pspring.datasource.password=${env.POSTGRES_DB_PASSWORD}
      -Pstandin.datasource.url=jdbc:postgresql://${env.NETWORK_ALIAS_SI}/${env.POSTGRES_DB_NAME}
      -Pstandin.datasource.username=${env.POSTGRES_DB_USER}
      -Pstandin.datasource.password=${env.POSTGRES_DB_PASSWORD}
      qaReporterUpload sonarCoverage --info

release:
  version_pattern: '\d{2}\.\d{3}\.\d{2}_\d{4}'
  version_init: 01.000.00_0000
  artifact_id: partners
  group_id: Nexus_PROD.CI02792425_sbbol-partners
  docker_registry: registry.sigma.sbrf.ru
  docker_prom: 'pprb/ci00908578/ci02792425_sbbol-partners'
  docker_dev: 'pprb-dev/ci00908578/ci02792425_sbbol-partners_dev'
  doc_path: 'docs/build/docs/'
  build_gradle:
    cpu: 2
    mem: '4g'
    command: >-
      ./gradlew
      -PnexusLogin=${env.NEXUS_USR}
      -PnexusPassword=${env.NEXUS_PWD}
      -Pversion=${env.VERSION}
      -Dtest-layer=unit,configuration,cdcConsumer,cdcProvider
      -Dpact.url=${env.PACT_BROKER_URL}
      -Dpactbroker.auth.username=${env.PACT_USER}
      -Dpactbroker.auth.password='${env.PACT_PASSWORD}'
      -Dpact.pacticipant.version=${env.VERSION}
      -Dpact.pacticipant.tag=${params.branch}
      -Dpactbroker.consumerversionselectors.tags=${settings.release.artifact_id}:${params.branch}
      -Dbuild.link=${env.BUILD_URL}
      -Dbuild.type=release
      -Dallure.link=${Const.ALLURE_ENTRYPOINT_URL}jobrun/${launch.jobRunId}
      -Dsonar.login=${env.SONAR_TOKEN}
      -Dsonar.branch.name=${params.branch}
      build qaReporterUpload sonarCoverage --parallel --info
  skip_istio: false
  default_values:
    params_branch: master
    istio_tag: '1.4'
    commit_or_tag: '01.002.00_0053'
    release_key:
    checkmarx: false
    reverse_and_publish: false
    type: develop
    params_folder: develop
