docker:
  images:
    java: registry.sigma.sbrf.ru/ci00149046/ci00405008_sbbolufs/bellsoft/liberica-openjdk-alpine:15.0.2-10-sber-certs
    postgres: registry.sigma.sbrf.ru/ci00149046/ci00405008_sbbolufs/postgres:13-alpine
    liquibase: registry.sigma.sbrf.ru/ci00149046/ci00405008_sbbolufs/liquibase/liquibase:3.10.3
    docs: registry.sigma.sbrf.ru/ci00149046/ci00405008_sbbolufs/bellsoft/liberica-openjdk-alpine:15.0.2-10-sber-certs

credentials:
  sonar: SA-SDVO0000346-sonar-token
  nexus: SA-SDVO0000346-nexus
  checkmarx: SA-SDVO0000346-checkmarx
  openshift: SA-SDVO0000346-openshift
  jenkins: SA-SDVO0000346-jenkins

project_name: sbbol-partners

pr_check:
  liquibase:
    match:
      files:
        - 'runner/src/main/resources/db/changelog'
    changelog:
      path: runner/src/main/resources/db/changelog/changelog.yaml
    defaults_file:
      path: jenkins/resources/liquibase/liquibase.properties
    command_type: update
  openshift:
    workdir: openshift
    match:
      files:
        - 'openshift/'
        - 'jenkins/resources/openshift/'
    server: dev-terra000006-idm.ocp
    namespace: ci02281165-sbbol-partners
  build_gradle:
    match:
      files:
        - 'migration-service/'
        - 'partners-adapter/'
        - 'partners-api/'
        - 'partners-openapi/'
        - 'partners-rest/'
        - 'partners-service/'
        - 'runner/'
        - 'buildSrc/'
        - 'docs/'
        - 'build.gradle.kts'
        - 'gradle.properties'
        - 'settings.gradle.kts'
    cpu: 1
    memory: '2g'
    command: >-
      ./gradlew
      -PnexusLogin=${env.NEXUS_USR}
      -PnexusPassword=${env.NEXUS_PWD}
      clean build -x test
  test:
    postgres: true
    match:
      files:
        - 'partners-adapter/'
        - 'partners-openapi/'
        - 'partners-service/'
        - 'buildSrc/'
        - 'docs/'
        - 'build.gradle.kts'
        - 'gradle.properties'
        - 'settings.gradle.kts'
        - 'jenkins/settings.yml'
        - 'jenkins/test.groovy'
    cpu: 2
    memory: '4g'
    command: >-
      ./gradlew
      -PnexusLogin=${env.NEXUS_USR}
      -PnexusPassword='${env.NEXUS_PWD}'
      -Dsonar.login=${env.SONAR_TOKEN}
      -Dsonar.projectVersion=${pullRequest.fromRef.displayId}
      -Dsonar.pullrequest.key=${params.pullRequestId}
      -Dsonar.pullrequest.branch=${pullRequest.fromRef.displayId}
      -Dsonar.pullrequest.base=${pullRequest.toRef.displayId}
      -Dtest-layer=unit,api,configuration,cdcConsumer
      -Dallure.jobrunId=${launch.jobRunId}
      -Dbuild.link=${env.BUILD_URL}
      -Dbuild.type=prCheck
      -Pspring.datasource.url=jdbc:postgresql://${env.NETWORK_ALIAS_MAIN}/${env.POSTGRES_DB_NAME}
      -Pspring.datasource.username=${env.POSTGRES_DB_USER}
      -Pspring.datasource.password=${env.POSTGRES_DB_PASSWORD}
      -Pstandin.datasource.url=jdbc:postgresql://${env.NETWORK_ALIAS_SI}/${env.POSTGRES_DB_NAME}
      -Pstandin.datasource.username=${env.POSTGRES_DB_USER}
      -Pstandin.datasource.password=${env.POSTGRES_DB_PASSWORD}
      qaReporterUpload sonarCoverage --info

release:
  version_pattern: '\d{2}\.\d{3}\.\d{2}_\d{4}'
  version_init: 02.000.00_0000
  artifact_id: partners
  group_id: Nexus_PROD.CI02792425_sbbol-partners
  docker_registry: registry.sigma.sbrf.ru
  docker_prom: 'pprb/ci00908578/ci02792425_sbbol-partners'
  docker_dev: 'pprb-dev/ci00908578/ci02792425_sbbol-partners_dev'
  doc_path: 'docs/build/docs/'
  skip_istio: false
  jira_project: DCBBRAIN
  default_values:
    parallel_build: true
    params_branch: master
    params_folder: develop
    istio_tag: '2.3'
    commit_or_tag: '01.002.00_0053'
    release_key: DCBBRAIN-1847
    checkmarx: false
    reverse_and_publish: false
    type: develop
  jobs:
    test_release:
      wait: false
  build_gradle:
    cpu: 2
    mem: '4g'
    command: >-
      ./gradlew
      -PnexusLogin=${env.NEXUS_USR}
      -PnexusPassword=${env.NEXUS_PWD}
      -Pversion=${env.VERSION}
      -Dbuild.link=${env.BUILD_URL}
      -Dbuild.type=release
      build -x test --parallel --info
  run_backend_tests: true
  run_frontend_tests: false
  test:
    allure_dir: build/allure-results
    email_list: DCB_BRAIN_NEW@sberbank.ru
    backend:
      command: >-
        ./gradlew
        -PnexusLogin=${env.NEXUS_USR}
        -PnexusPassword='${env.NEXUS_PWD}'
        -PsonarToken=${env.SONAR_TOKEN}
        -Pversion=${env.VERSION}
        build qaReporterUpload sonarCoverage
        -Dtest-layer=unit,api,configuration,cdcConsumer,cdcProvider
        -Dsonar.branch.name=${params.branch}
        -Dpactbroker.url=${env.PACT_BROKER_URL}
        -Dpactbroker.auth.username=${env.PACT_USER}
        -Dpactbroker.auth.password='${env.PACT_PASSWORD}'
        -Dpact.pacticipant.version=${env.VERSION}
        -Dpact.pacticipant.tag=${params.branch}
        -Dpact.consumer.tag=${params.branch}
        -Dpactbroker.consumerversionselectors.tags=${settings.project_name}:${params.branch}
        -Dversion=${env.VERSION}
        -Dbuild.link=${env.BUILD_URL}
        -Dbuild.type=release
        -Dallure.jobrunId=${launch.jobRunId}
