openapi: "3.0.0"
info:
  title: Request for renter
  version: DEV-SNAPSHOT
  description: OpenAPI Specification for renter

paths:
  /sbbol-partners/renter/create:
    $ref: create.yaml
  /sbbol-partners/renter/get:
    $ref: get.yaml
  /sbbol-partners/renter/update:
    $ref: update.yaml
  /sbbol-partners/renter/view:
    $ref: view.yaml
  /sbbol-partners/renter/version:
    $ref: version.yaml
