kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app: ingressgateway-${NAMESPACE}
    app.kubernetes.io/component: gateways
    app.kubernetes.io/instance: ${ISTIO_CONTROL_PLANE}
    app.kubernetes.io/managed-by: maistra-istio-operator
    app.kubernetes.io/name: gateways
    app.kubernetes.io/part-of: istio
    app.kubernetes.io/version: 2.0.2-3.el8-76
    chart: gateways
    heritage: Tiller
    istio: ingressgateway-${NAMESPACE}
    maistra-version: 2.0.2
    maistra.io/owner: ${ISTIO_CONTROL_PLANE}
    release: istio
  name: ingressgateway-${NAMESPACE}
spec:
  progressDeadlineSeconds: 1200
  replicas: ${INGRESS_REPLICAS_COUNT}
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: ingressgateway-${NAMESPACE}
      istio: ingressgateway-${NAMESPACE}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      labels:
        app: ingressgateway-${NAMESPACE}
        chart: gateways
        heritage: Tiller
        istio: ingressgateway-${NAMESPACE}
        release: istio
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - preference:
                matchExpressions:
                  - key: beta.kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
              weight: 2
            - preference:
                matchExpressions:
                  - key: beta.kubernetes.io/arch
                    operator: In
                    values:
                      - ppc64le
              weight: 2
            - preference:
                matchExpressions:
                  - key: beta.kubernetes.io/arch
                    operator: In
                    values:
                      - s390x
              weight: 2
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: beta.kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
                      - ppc64le
                      - s390x
      containers:
        - args:
            - proxy
            - router
            - --domain
            - ingressgateway-${NAMESPACE}.svc.cluster.local
            - --proxyLogLevel=warning
            - --proxyComponentLogLevel=misc:error
            - --log_output_level=default:info
            - --serviceCluster
            - ingressgateway-${NAMESPACE}
            - --trust-domain=cluster.local
          env:
            - name: ISTIO_META_UNPRIVILEGED_POD
              value: "true"
            - name: JWT_POLICY
              value: first-party-jwt
            - name: PILOT_CERT_PROVIDER
              value: istiod
            - name: CA_ADDR
              value: ${MESH_DISCOVERY_ADDRESS}.${ISTIO_CONTROL_PLANE}.svc:15012
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: INSTANCE_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.hostIP
            - name: SERVICE_ACCOUNT
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.serviceAccountName
            - name: CANONICAL_SERVICE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.labels['service.istio.io/canonical-name']
            - name: CANONICAL_REVISION
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.labels['service.istio.io/canonical-revision']
            - name: ISTIO_META_WORKLOAD_NAME
              value: ingressgateway-${NAMESPACE}
            - name: ISTIO_META_OWNER
              value: kubernetes://apis/apps/v1/namespaces/${NAMESPACE}/deployments/ingressgateway-${NAMESPACE}
            - name: ISTIO_META_MESH_ID
              value: cluster.local
            - name: ISTIO_META_ROUTER_MODE
              value: sni-dnat
            - name: ISTIO_META_CLUSTER_ID
              value: Kubernetes
          image: ${PROXY_IMAGE}
          imagePullPolicy: IfNotPresent
          name: istio-proxy
          ports:
            - containerPort: 15021
              name: status-port
              protocol: TCP
            - containerPort: 15443
              name: tls
              protocol: TCP
            - containerPort: 15012
              protocol: TCP
            - containerPort: 853
              protocol: TCP
            - containerPort: 15090
              name: http-envoy-prom
              protocol: TCP
            - containerPort: ${INGRESS_GEO_TLS_PORT}
              name: https-${INGRESS_GEO_TLS_PORT}
              protocol: TCP
            - containerPort: ${INGRESS_TLS_PORT}
              name: https-${INGRESS_TLS_PORT}
              protocol: TCP
            - containerPort: ${INGRESS_GEO_OTT_PORT}
              name: https-${INGRESS_GEO_OTT_PORT}
              protocol: TCP
            - containerPort: ${INGRESS_OTT_PORT}
              name: https-${INGRESS_OTT_PORT}
              protocol: TCP
          readinessProbe:
            failureThreshold: 30
            httpGet:
              path: /healthz/ready
              port: 15021
              scheme: HTTP
            initialDelaySeconds: 1
            periodSeconds: 2
            successThreshold: 1
            timeoutSeconds: 5
          resources:
            limits:
              cpu: ${INGRESS_LIMIT_CPU}
              memory: ${INGRESS_LIMIT_MEMORY}
              ephemeral-storage: ${INGRESS_PROXY_LIMIT_EPHEMERAL_STORAGE}
            requests:
              cpu: ${INGRESS_REQUEST_CPU}
              memory: ${INGRESS_REQUEST_MEMORY}
              ephemeral-storage: ${INGRESS_PROXY_REQUEST_EPHEMERAL_STORAGE}
          terminationMessagePath: /dev/termination-log
          volumeMounts:
            - mountPath: /etc/istio/proxy
              name: istio-envoy
            - mountPath: /etc/istio/config
              name: config-volume
            - mountPath: /var/run/secrets/istio
              name: istiod-ca-cert
            - mountPath: /etc/istio/pod
              name: podinfo
            - mountPath: /etc/istio/ingressgateway-certs
              name: ingressgateway-certs
              readOnly: true
            - mountPath: /etc/istio/ingressgateway-ca-certs
              name: ingressgateway-ca-certs
              readOnly: true
            - mountPath: /mnt/ott-uds-socket
              name: ott-uds-socket
          securityContext:
            readOnlyRootFilesystem: true
        - resources:
            limits:
              cpu: 400m
              memory: 500Mi
              ephemeral-storage: ${INGRESS_OTT_LIMIT_EPHEMERAL_STORAGE}
            requests:
              cpu: 300m
              memory: 300Mi
              ephemeral-storage: ${INGRESS_OTT_REQUEST_EPHEMERAL_STORAGE}
          terminationMessagePath: /dev/termination-log
          name: ott-sidecar
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 8443
              protocol: TCP
            - containerPort: 8778
              protocol: TCP
            - name: http-envoy-prom
              containerPort: 15090
              protocol: TCP
          imagePullPolicy: Always
          volumeMounts:
            - name: ott-secret
              readOnly: true
              mountPath: /mnt/secrets
            - name: ott-uds-socket
              mountPath: /mnt/ott-uds-socket
            - name: ott-logback
              readOnly: true
              mountPath: /tmp/ott-logback.xml
            - name: ott-tmp
              mountPath: /tmp
          terminationMessagePolicy: File
          envFrom:
            - secretRef:
                name: ott-ingress-passwords
            - configMapRef:
                name: cm-ingress-ott-settings
          image: ${OTT_REGISTRY_URL}
          securityContext:
            readOnlyRootFilesystem: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: default
      serviceAccountName: default
      terminationGracePeriodSeconds: 60
      volumes:
        - configMap:
            defaultMode: 420
            name: istio-ca-root-cert
          name: istiod-ca-cert
        - downwardAPI:
            defaultMode: 420
            items:
              - fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.labels
                path: labels
              - fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.annotations
                path: annotations
          name: podinfo
        - emptyDir: {}
          name: istio-envoy
        - configMap:
            defaultMode: 400
            name: cm-ingress-istio-basic
            optional: true
          name: config-volume
        - name: ingressgateway-certs
          secret:
            defaultMode: 400
            optional: true
            secretName: istio-ingressgateway-certs
        - name: ingressgateway-ca-certs
          secret:
            defaultMode: 400
            optional: true
            secretName: istio-ingressgateway-ca-certs
        - name: ott-secret
          secret:
            secretName: ott-secret
            defaultMode: 400
        - name: ott-uds-socket
          emptyDir:
            medium: Memory
        - name: ott-logback
          configMap:
            name: cm-ingress-ott-logback
            defaultMode: 400
        - name: ott-tmp
          emptyDir: { }
