apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: egress-db-main-gw
spec:
  selector:
    istio: egressgateway-${NAMESPACE}
  servers:
    - hosts:
        - ${MAIN_DB_HOST}
      port:
        name: tcp-${DB_TCP_PORT}
        number: ${DB_TCP_PORT}
        protocol: TCP