### Получение версии приложения
GET http://{{host}}/sbbol-partners/renter/version

### Получение Арендатора по digitalId и Id
POST http://{{host}}/sbbol-partners/renter/get
Content-Type: application/json

{
    "digitalId": "123456789",
    "uuid": "2fd15304-01c8-49f3-9eef-c3b32b96091f"
}

### Поиск Арендатора по digitalID
POST http://{{host}}/sbbol-partners/renter/view
Content-Type: application/json

{
    "digitalId": "999",
    "pagination": null
}

### Создание Арендатора
POST http://{{host}}/sbbol-partners/renter/create
Content-Type: application/json

{
    "uuid": "0210ca15-f792-4b02-b018-13f05e07d5f0",
    "type": "LEGAL_ENTITY",
    "digitalId": "123456789",
    "legalName": "ООО \"КРУИЗЫ\"",
    "inn": "7730522348",
    "kpp": "773001001",
    "ogrn": "1057746661312",
    "okpo": null,
    "lastName": null,
    "firstName": null,
    "middleName": null,
    "dulType": null,
    "dulName": null,
    "dulSerie": null,
    "dulNumber": null,
    "dulDivisionIssue": null,
    "dulDateIssue": null,
    "dulDivisionCode": null,
    "account": null,
    "bankBic": null,
    "bankName": null,
    "bankAccount": null,
    "phoneNumbers": null,
    "emails": "KEAfanasyeva@sberbank1.ru",
    "legalAddress": {
        "zipCode": null,
        "regionCode": null,
        "region": null,
        "city": null,
        "locality": null,
        "street": null,
        "building": null,
        "buildingBlock": null,
        "flat": null
    },
    "physicalAddress": {
    },
    "checkResults": null
}

### Обновление Арендатора
POST http://{{host}}/sbbol-partners/renter/update
Content-Type: application/json

{
  "uuid": "10f35493-5c74-40a6-b228-bfd1e2cb360e",
  "digitalId": "123456789",
  "type": "LEGAL_ENTITY",
  "legalName": "ООО \"КРУИЗЫ\"",
  "inn": "7730522348",
  "kpp": "773001001",
  "ogrn": "1057746661312",
  "emails": "KEAfanasyeva@sberbank1.ru",
  "legalAddress": {
  },
  "physicalAddress": {
  }
}
